name: Python Packaging Workflow

on:
  workflow_call:
    inputs:
      python-version:
        description: "Version of Python to use"
        required: false
        default: "3.13"
        type: string

      package-path:
        description: "Path to the Python script to validate"
        required: true
        type: string

jobs:
  package-python:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel

      # Build the package
      - name: Build the package
        run: python ${{ inputs.package-path }}/setup.py sdist bdist_wheel
  
      # Upload the artifact
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: python-package
          path: dist/
